apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '3300'
    prometheus.io/scrape: 'true'
  name: '{{ .projectName }}-online'
spec:
  ports:
    - name: http-service
      port: 80
      targetPort: service
    - name: service
      port: 3000
      targetPort: service
  selector:
    name: '{{ .projectName }}-online'
